### ISSUE TITLE
spawner.py fails to parse when multiple gpu types in same node

### ISSUE THREAD

**Issue by rob147147** [silx-kit/jupyterhub_moss#104]
Where a slurm compute node has multiple gpu types, as in my example below, the parser fails.

sinfo -a --noheader -o '%R %F %c %C %G %m %l' returns:
gpu-private 1/0/0/1 16 8/8/0/16 gpu:turing:1,gpu:ampere:3 257595 infinite

This fails in lines 131-134 of spawner.py which makes an assumption there is only 1 GPU type.

```
            try:
                gpus_gres = gpus.replace("(", ":").split(":")
                gpus_total = gpus_gres[2]
                gpu = ":".join(gpus_gres[0:2]) + ":{}"
```

gpus_total then becomes "1,gpu" and fails an integer check.

The easiest fix here is to split on commas first and then loop through the different types of GPU, but that will likely throw up more things to deal with further down the line.

**Comment by rob147147** [comment]
The same issue also causes an issue with nodes that might have some MIG enabled GPUs for example too: 

res-gpu-small 2/1/0/3 64 28/164/0/192 gpu:ampere:6(S:0-1),gpu:1g.10gb:28(S:0-1) 385411 infinite

This partition will not cause the parser to fail entirely as it will split on the colon that replaces the opening bracket, but the 1g.10gb type GPUs will just be ignored by the parser.

**Comment by t20100** [comment]
Hi,

Thanks for the feedback. Indeed multiple GPUs is not currently supported.

I'll fix the parsing for those cases but I'll keep the limitation of a single kind of GPU per partition (i.e., the user cannot choose from the UI the kind of GPUs to use or select a mix of multiple kinds of GPUs).

If you feel like proposing something to support multiple kind of GPUs selection from the UI, we can discuss it and a Pull Request is welcomed.

**Comment by t20100** [comment]
I made PR #105 which should fix the parsing issue you encounter.

**Comment by t20100** [comment]
I'm closing this issue: PR #105 fixed the parsing issue, and there is already and issue opened for multiple GPUs support (see #97)
