### ISSUE TITLE
sbatch: error: Invalid --mem specification

### ISSUE THREAD

**Issue by elia427** [silx-kit/jupyterhub_moss#109]
Hi,

Thanks for this useful stuff. I have this in my jupyterhub configuration file:

`#SBATCH --time={runtime}
#SBATCH --nodes 1
#SBATCH --ntasks={nprocs}
#SBATCH --mem={memory}
#SBATCH --partition={partition}
#SBATCH --job-name=jupyterhub
#SBATCH --chdir={homedir}
#SBATCH --export={keepvars}
#SBATCH --get-user-env=L
#SBATCH --oversubscribe
#SBATCH --reservation={reservation}

I get `sbatch: error: Invalid --mem specification` when i use the simple mode. 
Good  hint is explained [here](https://researchcomputing.princeton.edu/support/knowledge-base/memory). It seems Jupyterhub_moss is passing invalid integer or parameter when it is in simple mode.

Thanks for the help.

Best,
Elia

**Comment by elia427** [comment]
Hi,

Thank you for looking into this. Did you mean to remove `#SBATCH --mem={memory}?` If that's what you meant, removing that parameter indeed solved the issue. I no longer receive the error message that I used to get when using Simple mode. However, the problem arises when I use the Advanced option. In that case, jupyterhub_moss doesn't pass the 8G parameter that I enter in the `Total memory (--mem): `field. Slurm always defaults to `ReqTRES=cpu=1,mem=3000M,node=1,billing=1`, regardless of how much memory I specify. As a result, my jobs are getting killed because they use more than the default 3G of memory.

Best,
Elia

**Comment by t20100** [comment]
No I was meaning, that it's best if you can avoid overriding the `batch_script`, and if you have to override it, it should be similar to/compatible with the default one.

For instance for `memory`, use this:
```
{% if memory     %}#SBATCH --mem={{memory}}
{% endif %}
```
instead of `#SBATCH --mem={{memory}}` alone.

**Comment by elia427** [comment]
Thank you!
