### ISSUE TITLE
Error when I try to install jupyterhub_moss

### ISSUE THREAD

**Issue by HanyMostafa** [silx-kit/jupyterhub_moss#110]
When I run the command (pip install jupyterhub_moss) to install jupyterhub_moss  I got the following error, 

ERROR: Could not find a version that satisfies the requirement jupyterhub_moss

When I tried to use git 

pip install git+https://github.com/silx-kit/jupyterhub_moss.git

I got the following error :

ERROR: Could not find a version that satisfies the requirement pydantic<3,>=2.0 (from jupyterhub-moss) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7, 0.7.1, 0.8, 0.9, 0.9.1, 0.10, 0.11, 0.11.1, 0.11.2, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.15, 0.16, 0.16.1, 0.17, 0.18, 0.18.1, 0.18.2, 0.19, 0.20a1, 0.20, 0.20.1, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27a1, 0.27, 0.28, 0.29, 0.30, 0.30.1, 0.31, 0.31.1, 0.32, 0.32.1, 0.32.2, 1.0b1, 1.0b2, 1.0, 1.1, 1.1.1, 1.2, 1.3, 1.4, 1.5, 1.5.1, 1.6, 1.6.1, 1.6.2, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8, 1.8.1, 1.8.2, 1.9.0a1, 1.9.0a2, 1.9.0, 1.9.1, 1.9.2)
ERROR: No matching distribution found for pydantic<3,>=2.0

P.S I already have a working jupyterhub

**Comment by t20100** [comment]
The issue looks to come from installing `pydantic` v2 (try `pip install pydantic>=2`). What version of Python do you use? Maybe it's too old for recent versions of `pydantic` (3.8+ is needed for `jupyterhub_moss` and 3.7+ for `pydantic` v2). 

BTW, did you try `pip install jupyterhub_moss` directly?

**Comment by HanyMostafa** [comment]
Thank you for reply this is was my first try to install it using pip install jupyterhub_moss 
and I got the below error 

ERROR: Could not find a version that satisfies the requirement jupyterhub_moss (from versions: none)
ERROR: No matching distribution found for jupyterhub_moss

**Comment by t20100** [comment]
It's most likely a too old version of Python then

**Comment by HanyMostafa** [comment]
I updated python to 3.9 and it worked fine, but when I logged out from jupyterhub and tried to login again it gave me this error 

403 : Forbidden
'_xsrf' argument missing from POST

The login page is integrated  with active directory.

**Comment by HanyMostafa** [comment]
I tried the following solutions 

c.NotebookApp.disable_check_xsrf = True

--ServerApp.disable_check_xsrf=True  --allow_remote_access=true

but nothing works

**Comment by t20100** [comment]
I don't recall encountering such issue.

Not sure it's related, but as of today, there are some compatibility issues between batchspawner and jupyterhub: batchspawner latest release (v1.2) is not compatible with jupyterhub >=3 (https://github.com/jupyterhub/batchspawner/issues/277). If you use jupyterhub>=3, you need to install batchspawner from the git repository.

**Comment by HanyMostafa** [comment]
I used Esaybuild to install jupyterHUb 4.0.1 , Python 10.3

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/j/JupyterHub/JupyterHub-4.0.1-GCCcore-12.2.0.eb

then I installed jupyterhub _moss using "pip install jupyterhub_moss"  and configurated the partitions and now its working, I will do the rest of the configuration and let you updated 

Thank you
