### ISSUE TITLE
form rendering with Jupyterhub 5

### ISSUE THREAD

**Issue by rclUPC** [silx-kit/jupyterhub_moss#111]
Hi,
I have installed jupyterhub-moss in a new system, and it was not working. Spawn forms was not displayed. Finally I have realized that jupyterhub 5 (which is the one installed in the new computer) has [migrated from LESS to SASS with the new version of bootstrap](https://jupyterhub.readthedocs.io/en/5.0.0/howto/upgrading-v5.html#bootstrap-5).
Instead of changing the code, I decided to downgrade jupyterhub to version 3.1.1, but I think it should be considered for the new versions.
BTW, thank you for this awesome package.
Robert

**Comment by rclUPC** [comment]
Thank you. I will test it....

**Comment by t20100** [comment]
Thanks! Let us know how it goes.

**Comment by t20100** [comment]
There is a new release which fix this: https://pypi.org/project/jupyterhub-moss/9.0.0/
Let us know if it works fine for you.
