### ISSUE TITLE
LocalProcessSpawner cannot be used

### ISSUE THREAD

**Issue by TerenceLiu98** [silx-kit/jupyterhub_moss#18]
Thanks for developing this package, it is a good-designed spawner for HPC and Jupyterhub.

I am wondering if `jupyterhub_moss` can allocate the local machine, for example the `wrapsapwner.ProfilesSpawner` can use `jupyterhub.spawner.LocalProcessSpawner`. Is there any way in `jupyterhub_moss`?

**Comment by t20100** [comment]
Hi,

We've made `jupyterhub_moss` for working with the SLURM `batchspawner`.
It should be possible to make it work with other schedulers supported by [batchspawner](https://github.com/jupyterhub/batchspawner), but not with others.

**Comment by TerenceLiu98** [comment]
> Hi,
> 
> We've made `jupyterhub_moss` for working with the SLURM `batchspawner`.
> It should be possible to make it work with other schedulers supported by [batchspawner](https://github.com/jupyterhub/batchspawner), but not with others.

Thanks, I have solved the problem by installing the `batchspawner`, but I forgot to close this issue. :)
