### ISSUE TITLE
Settings are no longer persisted when toggling from Simple to Advanced

### ISSUE THREAD

**Issue by loichuder** [silx-kit/jupyterhub_moss#35]
## How to reproduce
- Go to https://jupyter-slurm.esrf.fr/hub/spawn
- Change some settings in the Simple Tab
- Launch a job
- Relinquish the job
- Go back to https://jupyter-slurm.esrf.fr/hub/spawn → _The settings were persisted thanks to #27_
- Go to the Advanced tab
- Go back to the Simple tab → **Settings are back to default !**

**Comment by t20100** [comment]
Indeed, there is a reset of the form when switching from Advanced to Simple to simplify the implementation.
What should be possible without too much changes is to check if persisted config was a simple one and restore it when switching back to Simple, if it was an advanced one, then only reset.
