### ISSUE TITLE
Add/remove button style issue on old firefox

### ISSUE THREAD

**Issue by t20100** [silx-kit/jupyterhub_moss#47]
With firefox 68.9.0 (debian8) and 78.13 (debian10), the buttons does not look good (much bigger than expected):
![Screen Shot 2022-01-24 at 16 37 12](https://user-images.githubusercontent.com/9449698/150814234-0a60efef-ee26-408f-9de0-f88d8737128f.png)

It is fine with up-to-date versions...

**Comment by t20100** [comment]
This is getting worst:
![Screen Shot 2022-01-27 at 10 33 19](https://user-images.githubusercontent.com/9449698/151331698-1e6b4878-3858-45e9-b94e-7b1d7e6b5783.png)

And from a look at the inspector it does not respects the layout:

![Screen Shot 2022-01-27 at 10 39 22](https://user-images.githubusercontent.com/9449698/151332779-170d67e3-b7fc-431b-a508-e2fa448c70b8.png)


@axelboc @loichuder is there a simple way to fix this for older browser here? Can this be due to minimum size for text input and button?

The html of the add custom div is here:

https://github.com/silx-kit/jupyterhub_moss/blob/d9ecab067a1bb9ccfb170ab24fdc310b299860f9/jupyterhub_moss/templates/option_form.html#L215-L251

And the CSS:

https://github.com/silx-kit/jupyterhub_moss/blob/d9ecab067a1bb9ccfb170ab24fdc310b299860f9/jupyterhub_moss/form/option_form.css#L114-L154

**Comment by axelboc** [comment]
Probably because you're missing `flex` on the first text input. By default, flex children have `flex: 0 1 auto`, which basically says don't shrink past the width of the element. Since the browser gives `input` elements a width, it doesn't shrink sufficiently. Try setting `flex: 1 1 0%` on both inputs (equivalent to `flex: 1`). If that doesn't work, try `min-width: 0` as well so they can shrink past their intrinsic width.

**Comment by axelboc** [comment]
Not sure why the buttons are big though. Try looking at our button clean-up code in H5Web: https://github.com/silx-kit/h5web/blob/main/packages/shared/src/utils.css#L1

**Comment by axelboc** [comment]
Maybe something to do with `box-sizing: content-box` (i.e. the browser's default value) instead of `box-sizing: border-box`?

**Comment by t20100** [comment]
Actually, setting `padding: 0` on the buttons fixes both alignment and button size issues.
Thanks for all the hints.
