### ISSUE TITLE
Problems with jupyterhub configuration file

### ISSUE THREAD

**Issue by rclUPC** [silx-kit/jupyterhub_moss#67]
Hi,
first of all, thank you for the project. 
Unfortunately, I have been not able to get it working. I have a jupyterhub server in our small slurm cluster (just 3 nodes), but I couldn't configure properly the jupyterhub config file.
The public ip of the server is, say, 10.5.32.234. I can connect to jupyterhub in this address, https://10.5.32.234.
Also, this same server is, inside the cluster, 10.10.10.1 (the master). The other nodes (slaves) are 10.10.10.2, 10.10.10.3 and 10.10.10.4. 
My question is, how  do I have to configure jupyterhub and the spawner so that the singleuser server can be accessed through 10.5.32.234?
I have tested it in many ways. The only thing I get is that the server starts in the local ip address of the single user server:  http://127.0.0.1:57573, but the jupyterhub page does not connect:
![image](https://user-images.githubusercontent.com/26278027/207566928-d6ae3724-87d4-4a53-82d0-bce5475835ef.png)
Some configuration item is missing, but I don't known which one.
With regards
Robert

**Comment by t20100** [comment]
Hi,

You probably need to set `c.JupyterHub.hub_ip` to `10.10.10.1` in your case so the singleuser servers can connect to it because they are not on the same host (see https://jupyterhub.readthedocs.io/en/stable/api/app.html#jupyterhub.app.JupyterHub.hub_ip)

Also what are the logs of the jupyterhub server and singleuser servers?

**Comment by rclUPC** [comment]
Hi, Thomas,
This is the configuration I am using:
```
# HUB CONFIGURATION

c.JupyterHub.log_level = 'DEBUG'

# Allow servers to persist between restarts of the hub itself
c.JupyterHub.cleanup_servers = False

# We're doing SSL through the Hub's built-in capabilities, so host on 443
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.port = 443

# Make sure that the remote notebook servers can contact the hub
c.JupyterHub.hub_ip = '10.10.10.1'

c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/jupyterhub_cookie_secret'

c.JupyterHub.db_url = '/etc/jupyterhub/jupyterhub.sqlite'
```
it should work, according to your comment. But it doesn't.

I attach the log for the jupyterhub, and the single user sever

[slurm-10056.txt](https://github.com/silx-kit/jupyterhub_moss/files/10231600/slurm-10056.txt)

[jupyterhub.log](https://github.com/silx-kit/jupyterhub_moss/files/10231586/jupyterhub.log)

**Comment by t20100** [comment]
Hi,

Try to use `jupyterhub` <3.0 (e.g. 2.3.1) on the jupyter singleuser server side (in `/opt/env/bin` in your case).
We're still using v2.3.0 and I have the same issue and the same `RuntimeWarning` if I upgrade to `jupyterhub` to v3.x:

```
/opt/env/lib/python3.8/site-packages/batchspawner/singleuser.py:17: RuntimeWarning: coroutine 'HubAuth._api_request' was never awaited
  hub_auth._api_request(
```

If it works for you with 2.3.1 it would be good to check if there is already an issue opened on jupyterhub and eventually open one.

**Comment by rclUPC** [comment]
Hi 
I have tried with 2.3.1 and 2.3.0 in both sides (server and environment) with this configuration:
'''
# Sample jupyterhub configuration using jupyterhub_moss

import os
import random
import sys

import batchspawner  # noqa

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

import jupyterhub_moss  # noqa

c = get_config()  # noqa

# Select the MOSlurmSpawner backend
jupyterhub_moss.set_config(c)


class MOckSlurmSpawner(jupyterhub_moss.MOSlurmSpawner):
    async def _get_slurm_info(self):
        return {
            k: {
                "nodes": v["max_nprocs"],
                "idle": random.randint(0, v["max_nprocs"]),
                "max_mem": 128000 * (index + 1),
            }
            for index, (k, v) in enumerate(self.partitions.items())
        }


c.JupyterHub.spawner_class = MOckSlurmSpawner
# Partition descriptions, see https://github.com/silx-kit/jupyterhub_moss#partition-settings
c.MOSlurmSpawner.partitions = {
    "debug": {
        "architecture": "x86_86",
        "description": "Partition DEBUG",
        "gpu": None,
        "max_ngpus": 0,
        "max_nprocs": 96,
        "max_runtime": 12 * 3600,
        "simple": True,
        "jupyter_environments": {
            "default": {
                "path": "/opt/env/bin/",
                "description": "Operating system (default)",
                "add_to_path": False,
            },
        },
    },
}


# JupyterHub
c.JupyterHub.ip = "10.7.4.243"
c.JupyterHub.hub_ip = "10.10.10.1"
c.JupyterHub.port = 443
c.JupyterHub.ssl_cert = '/etc/ssl/certs/flexicast_upc_edu_cert.cer'
c.JupyterHub.ssl_key = '/etc/ssl/private/flexicast.upc.edu.key'
c.JupyterHub.hub_connect_ip = '10.10.10.1'

# Batchspawner
# c.BatchSpawnerBase.exec_prefix = ""  # Do not run sudo
'''
but still does not work. It raises an error 'coroutine' object is not subscriptable'

I attach the log file
[jupyterhub.log](https://github.com/silx-kit/jupyterhub_moss/files/10235569/jupyterhub.log)

**Comment by rclUPC** [comment]
Solved. I didn't install JupyterLab in the local environment. Now it is working. 
Summarizing... It worked with the Anaconda3 distribution, with jupyterhub 2.3.0, and the last version (from git repos) of batchspawner and jupyterhub_moss
Nice package. Thank you

**Comment by t20100** [comment]
Hi,

Good to hear it's progressing!

The issue here looks to be that you installed a release of `jupyterhub_moss`  but used the demo config file from github.
Since the latest version, there has been changes in the repository regarding usage of `async`.

So it should work by either installing the project from the repository or using the following:
https://github.com/silx-kit/jupyterhub_moss/blob/afa0f8f17ec9ce588b159fdfa5fc4a0bb65e052f/demo_jupyterhub_conf.py#L19-L28
from [v5.0.0/demo_jupyterhub_conf.py](https://github.com/silx-kit/jupyterhub_moss/blob/v5.0.0/demo_jupyterhub_conf.py)
