### ISSUE TITLE
Remove `add_to_path` from configuration?

### ISSUE THREAD

**Issue by t20100** [silx-kit/jupyterhub_moss#76]
As PR #74 adds a `prologue` environment configuration, it is now possible to set the `PATH` with `prologue` rather than through `add_to_path`.
This is a bit more complicated from the configuration side and simplifies a bit the code.

Is it worth removing `add_to_path` and thus making a breaking change?

**Comment by loichuder** [comment]
I would tend to disagree.

I find it is a handy shortcut over writing the `export` in `prologue`. The resulting code is not awfully complex either.

**Comment by t20100** [comment]
Agreed, it is little code on `jupyterhub_moss` side.

**Comment by loichuder** [comment]
Yeah, I know I [complained](https://github.com/silx-kit/jupyterhub_moss/pull/71#discussion_r1082201398) [a bit](https://github.com/silx-kit/jupyterhub_moss/pull/74#discussion_r1084157123) but this is just my grumpy side showing :smile_cat:
