### ISSUE TITLE
Support for environment modules

### ISSUE THREAD

**Issue by lexming** [silx-kit/jupyterhub_moss#98]
We rely on environment modules to provide our users with different versions of JupyterLab and Python. Therefore there is no need to define any path (*i.e.* use any conda or virtual environment) to launch the single user server.

All we need is to add some `module load` commands in the prologue of the job script.

**Comment by t20100** [comment]
It makes sense not to rely on the path in this case.

A per-environment "prologue" has been added recently and can be used to run `module load ...` (see https://github.com/silx-kit/jupyterhub_moss#field-descriptions)

**Comment by lexming** [comment]
Yes, I've seen the addition of *prologue* as a configurable environment setting. That's a nice addition!

In the case of modules, we prefer to use a specific setting for it though. That allows users to define the modules in their environment with a simple space-separated list of module names from the advanced panel.

**Comment by t20100** [comment]
> In the case of modules, we prefer to use a specific setting for it though. That allows users to define the modules in their environment with a simple space-separated list of module names from the advanced panel.

Sure, it makes sense!
